### ISSUE TITLE
usage ? python flooder.py -h python flooder.py domain.com ?

### ISSUE THREAD

**Issue by darknodi** [transilvlad/flooder#1]

**Comment by transilvlad** [comment]
Can you describe the issue please?

**Comment by darknodi** [comment]
the scenarious for this script. use from this scenarious script .

open terminal 

@transilvlad

**Comment by darknodi** [comment]
@transilvlad are you here

**Comment by transilvlad** [comment]
What exactly are you talking about?

**Comment by darknodi** [comment]
from one domain service provider that provides internet, from the script. 

finding dns servers from this domain... 

8 dns servers active
would you want to flood ? y/n 

y 

sending SYN/ACK TPC to these dns servers..... 

CTRL c stop. 

to floods dns servers, that lan's computers of gaming center, to go offline, timed out.

@transilvlad

**Comment by transilvlad** [comment]
This is a testing tool not an attacking tool.
The point was to test HTTP API's in a controlled environment.
Also Python 2.7 is END OF LIFE in 11 days.
